#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Write site/js/licenses.js, the license and exception identifiers the listing
page accepts, from the same license-expression list that check_license.py uses.

Run it after a change to the license-expression pin in requirements.txt.
test_vectors.py fails while the file is out of date.
"""

import json
import re
import sys
from importlib.metadata import version
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import check_license

TARGET = Path(__file__).resolve().parent.parent / "site" / "js" / "licenses.js"


def identifiers():
    """The license and the exception identifiers, without the ones the page
    accepts through the LicenseRef rule or cannot read as one token."""
    licenses = set()
    exceptions = set()
    for symbol in check_license.licensing().known_symbols.values():
        for name in (symbol.key, *symbol.aliases):
            if re.search(r"\s", name) or check_license.LICENSE_REF.match(name):
                continue
            (exceptions if symbol.is_exception else licenses).add(name)
    order = lambda name: (name.lower(), name)
    return sorted(licenses, key=order), sorted(exceptions, key=order)


def render():
    licenses, exceptions = identifiers()
    listed = lambda names: "".join(f"  {json.dumps(name)},\n" for name in names)
    return (
        f"// Generated by tools/page_licenses.py from license-expression "
        f"{version('license-expression')}. Do not edit.\n"
        f"export const LICENSES = [\n{listed(licenses)}];\n"
        f"export const EXCEPTIONS = [\n{listed(exceptions)}];\n"
    )


def main():
    TARGET.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(TARGET.parents[2]).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
