spec_version = 1
id = "Compendium"
type = "mod"
name = "Compendium"
authors = ["nanonestor"]
abstract = "Compendium adds a window (which may be toggled on/off via ModMenu) which provides a helpful companion to exploring the currently loaded solar system!"
description = """
Compendium adds a window (which may be toggled on/off via ModMenu) which provides a helpful companion to exploring the currently loaded solar system!

- Solar system bodies (celestials) are listed in categories and tiered based on parent bodies and their satellites (moons/moonlets).  
- Orbit lines have toggle buttons for individual bodies, groups of bodies, and entire categories.  
- Fun and useful information is displayed regarding each body's stats.  
"""
license = "MIT"
tags = ["user-interface"]

[releases]
github = "meow-sci/Compendium"
spacedock = 4074
authority = "spacedock"

[links]
forums = "https://forums.ahwoo.com/forums/kitten-space-agency/mod-releases/compendium.647/"
repository = "https://github.com/meow-sci/Compendium"
spacedock = "https://spacedock.info/mod/4074/Compendium"
bugtracker = "https://github.com/meow-sci/Compendium/issues"

[compatibility]
game_min = "2026.9.7.5402"

[loader]
id = "StarMap"
min = "0.4.6"

[images.icon]
url = "https://raw.githubusercontent.com/meow-sci/Compendium/refs/heads/main/src/Photos/Compendium-icon-512x512.png"
sha256 = "3adb3ece1ef4c2f4826e55ee8d4fc6027ab49e54bc50be754fe41b09a0e4b9e6"
width = 512
height = 512
size = 184473
