spec_version = 1
id = "KittenExtensions"
type = "mod"
name = "KittenExtensions Continued"
authors = ["AMPW"]
abstract = "XML Patching (ModuleManager like), Custom XML Assets"
description = """
# KittenExtensions Continued

This is a continuation of tom_is_unlucky's awesome KittenExtensions mod. All of the credit goes to him. It's a replacement with the same mod and directory name, only the SpaceDock name is different.

    Write XML patches to alter xml assets from core or other mods
    Add custom xml asset types that can be used in other mods

Visit the Forum Thread and Github Repo for more information.
"""
license = "MIT"
tags = ["tools","library"]

[releases]
github = "AMPW-german/KittenExtensions"
spacedock = 4588
authority = "github"

[links]
forums = "https://forums.ahwoo.com/forums/kitten-space-agency/mod-releases/kittenextensions-continued-v0-5-0-xml-patching-modulemanager-like-custom-xml-assets.1259/"
repository = "https://github.com/AMPW-german/KittenExtensions"
spacedock = "https://spacedock.info/mod/4588/KittenExtensions%20Continued"
bugtracker = "https://github.com/AMPW-german/KittenExtensions/issues"

[compatibility]
game_min = "2026.9.10.5438"

[loader]
id = "StarMap"
min = "0.4.7"
