spec_version = 1
id = "KSA_SeaDragon"
type = "mod"
name = "Sea Dragon"
authors = ["Spaceman_3D"]
abstract = "Adds the Sea Dragon Rocket to KSA"
license = "GPL-3.0"
tags = ["parts"]

[releases]
spacedock = 4593

[links]
forums = "https://forums.ahwoo.com/forums/kitten-space-agency/mod-releases/sea-dragon.1263/"
spacedock = "https://spacedock.info/mod/4593/Sea%20Dragon"

[compatibility]
game_min = "2026.9.22.5482"

[images.icon]
url = "https://aa5e8942dc923bc6bb7f40be4f2e4a41.r2.cloudflarestorage.com/forums-production-public-data/attachments/2/2038-5c0024f6e359bdf5b3d5f532408a6cdc.data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=5957d47e4aaceae7f1cbe5a8a160c95d%2F20260926%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20260926T131045Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&response-content-disposition=inline%3B%20filename%3D%22Screenshot%202026-09-26%20120749.jpg%22&response-content-type=image%2Fjpeg&X-Amz-Signature=583477b3fe8c92f1d76480072d671b4197962fbfa5d2832f9cb76a28d40d71d1"
sha256 = "88305f1d5ab5f42c9b2f71f0ba2e065e382bd9a7f324dd11c66cfc021776bf40"
width = 431
height = 431
size = 24827
