spec_version = 1
id = "KSA_SeaDragon"
type = "mod"
name = "Sea Dragon"
authors = ["Spaceman_3D"]
abstract = "Adds the Sea Dragon Rocket to KSA"
license = "GPL-3.0"
tags = ["parts"]

[releases]
spacedock = 4593

[links]
forums = "https://forums.ahwoo.com/forums/kitten-space-agency/mod-releases/sea-dragon.1263/"
spacedock = "https://spacedock.info/mod/4593/Sea%20Dragon"

[compatibility]
game_min = "2026.9.22.5482"

[images.icon]
url = "https://aa5e8942dc923bc6bb7f40be4f2e4a41.r2.cloudflarestorage.com/forums-production-public-data/attachments/2/2036-2cd3ccfe9e51bdac68bab01d2db66a25.data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=5957d47e4aaceae7f1cbe5a8a160c95d%2F20260926%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20260926T120010Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&response-content-disposition=inline%3B%20filename%3D%22Screenshot%202026-09-26%20120749.jpg%22&response-content-type=image%2Fjpeg&X-Amz-Signature=525672490581ae690c195a91e5b503666626f88865d20520ee0ee8259f60fac5"
sha256 = "b4cdc196eec34090815fed79b4e3f4d35585d846707226359bceec7dd9ce952f"
width = 841
height = 1000
size = 74708
attribution = "Spaceman 3D"
